// USD source of truth (from RynSpireEdu K12 Price List USD 2025)
export const PLANS = [
  {
    key: "hourly",
    name: "Hourly Plan",
    priceUsd: 39.99,
    perLabel: "per class",
    tag: "Try one class",
    sessions: 1,
    features: [
      "1 × 60-minute 1-to-1 class",
      "Any K-12 subject",
      "Pay as you go",
      "Perfect after your free demo",
    ],
    highlight: false,
  },
  {
    key: "monthly",
    name: "Monthly",
    priceUsd: 424.99,
    perLabel: "per month",
    tag: "21 classes / month",
    sessions: 21,
    perSessionUsd: 20.23,
    features: [
      "21 × 60-minute 1-to-1 classes",
      "English, Math & Science",
      "Weekly progress reports",
      "Tests, worksheets & knowledge base",
      "Flexible scheduling",
    ],
    highlight: false,
  },
  {
    key: "quarterly",
    name: "Quarterly",
    priceUsd: 1199.99,
    perLabel: "every 3 months",
    tag: "Save 6%",
    sessions: 63,
    perSessionUsd: 19.04,
    features: [
      "63 × 60-minute 1-to-1 classes",
      "Everything in Monthly",
      "Priority tutor matching",
      "Porter Assessment",
    ],
    highlight: true,
    saveUsd: 75,
    discountPct: 6,
  },
  {
    key: "halfyearly",
    name: "Half-Yearly",
    priceUsd: 2199.99,
    perLabel: "every 6 months",
    tag: "Save 8%",
    sessions: 126,
    perSessionUsd: 17.46,
    features: [
      "126 × 60-minute 1-to-1 classes",
      "Everything in Quarterly",
      "Dedicated academic coordinator",
    ],
    highlight: false,
    saveUsd: 200,
    discountPct: 8,
  },
  {
    key: "yearly",
    name: "Yearly",
    priceUsd: 3999.99,
    perLabel: "every year",
    tag: "Best value · Save 9%",
    sessions: 252,
    perSessionUsd: 15.87,
    features: [
      "252 × 60-minute 1-to-1 classes",
      "Everything in Half-Yearly",
      "Full year revision roadmap",
    ],
    highlight: false,
    saveUsd: 400,
    discountPct: 9,
  },
];

export const PLAN_INCLUDES = [
  "1-on-1 tutoring in English, Math & Science",
  "Knowledge Base",
  "Porter Assessment",
  "Tests & Worksheets",
  "Performance Reports",
  "Flexible Scheduling",
];
